name: Check deno code

on: workflow_call

jobs:
  check-deno-code:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
      - run: deno task fmt:check
      - run: deno task check
      - run: deno task lint
