name: Generate README from pod

on:
  push:
    paths:
      - "README.pod"

jobs:
  Run-deno-task-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate readme
        run: deno task readme
      - run: cat README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ":package: update deno dependencies"
          title: Update Deno Dependencies
          add-paths: README.md
          body: |
            This PR is created by [create-pull-request](https://github.com/peter-evans/create-pull-request).
            The `README.md` is generated automaticaly.
          author: GitHub-Action <noreply@github.com>
          delete-branch: true
