name: Generate README from pod

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "README.pod"

jobs:
  Run-deno-task-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: denoland/setup-deno@916edb9a40fd86d1ff57b758807ebe57242f7407 # 1.4.0
        with:
          deno-version: vx.x.x
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Generate readme
        run: deno task readme
      - run: cat README.md
      - name: Create commits
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git add README.md --force
          git commit -m "docs: Generate README.md"
          git clean -fdx
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          title: ":robot: Update README.md"
          body: |
            This PR is created by [create-pull-request](https://github.com/peter-evans/create-pull-request).
            The `README.md` is generated automaticaly.
          author: "GitHub <noreply@github.com>"
          delete-branch: true
