name: Generate README from pod

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "README.pod"

jobs:
  Run-deno-task-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd # v2.0.0
        with:
          deno-version: vx.x.x
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Generate readme
        run: deno task readme
      - run: cat README.md
      - name: Create commits
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git add README.md --force
          git commit -m "docs: Generate README.md"
          git clean -fdx
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          title: ":robot: Update README.md"
          body: |
            This PR is created by [create-pull-request](https://github.com/peter-evans/create-pull-request).
            The `README.md` is generated automaticaly.
          author: "GitHub <noreply@github.com>"
          delete-branch: true
